[package]
name = "hello-ltrait"
version = "0.1.0"
edition = "2024"

[dependencies]
ltrait = "0.10.0"
ltrait-ui-tui = { git = "https://github.com/ltrait/ui-tui", version = "0.1.0" }
tokio = { version = "1.44.1", features = ["full"] }
