name = "hello-aeneas"
version = "0.1.0"
defaultTargets = ["hello-aeneas"]

# [[require]]
# name = "aeneas"
# path = "./.aeneas/backends/lean"

[[require]]
name = "aeneas"
git = { url = "https://github.com/AeneasVerif/aeneas", subDir = "backends/lean" }
rev = "852977db16ae4a8fecd4597097a2d98f5bd11a18"

[[lean_lib]]
name = "HelloAeneas"

[[lean_exe]]
name = "hello-aeneas"
root = "Main"
